Milestone 2: Components and Redux Store
AndresFMoya/react-bookstore pull request #2
Opened 2020-01-15 19:35 UTC by AndresFMoya

Hello TSEs,

In this milestone, project components were initialized as follows:

- Inside **src** folder, four directories were created: **components**, **container**, **actions** and **reducers**.
- `App` component was implemented. It wraps `BooksList` and `BooksForm`. The `App` component is attached to the main index render function.
- `BooksList` component was implemented. It displays the books as a html table. It's connected to the Redux Store and fetch the books from the state, using the `connect()` function.
- `Book` component was implemented. It represents a single book.
- `BooksForm` component was created aswell. It renders a simple form to add books.
- Redux `actions` and `reducers` were defined.
- Redux `store` was initialized in the main index file. Each book has a unique ID generated with _Math.random_.
- `App` component is rendered wrapped in `Provider` to make the Redux store available to all components.

Currently, the app looks like this: </br></br>
<div align="center">
<img width="331" alt="Screen Shot 2020-01-15 at 2 00 10 PM" src="https://user-images.githubusercontent.com/49841637/72464600-95c2f400-37a3-11ea-90ca-5e9e4109657f.png"></div>

Looking to hear your comments.

Best!

Andres Moya

2020-01-15 21:11 UTC, shloch requested changes
## Hello @AndresFMoya , 
Nice job, good code and guidelines respected
Please fix little issue below and file for last re-review
Happy coding

2020-01-15 21:11 UTC, shloch commented on src/components/BooksForm.js
> +export default BooksForm;
this is a "container" component, pleace is inside `src/containers/` folder 😊
(meaning you will have to change couple IMPORTS where this component is used)

2020-01-15 21:11 UTC, shloch commented on src/components/BooksForm.js
> +export default BooksForm;
Also initialise state here with `title` and `category`

2020-01-15 21:22 UTC, AndresFMoya commented
Hi @shloch. Thanks for your comments.

The `BooksForm` component was moved to **container** folders. The state is initialized in the first step of next milestone since it is not going to be used in this one, linter raises an unused function var.

Looking to hear your comments!

2020-01-16 12:44 UTC, jofer86 approved these changes
## 👋 👋 Hello! @AndresFMoya just dropping by to do the follow up to the previous review!

- Looks like everything is taken care of!! you might move along now!! 👍 👍 👍  Approved!

2020-01-16 13:21 UTC, merged